#! /usr/bin/env ruby
# because rubygems shims assume a gem's executables are Ruby

require "sqlpkg/commands"

begin
  command = [Sqlpkg::Commands.executable, *ARGV]
  puts command.inspect
  exec(*command)
rescue Sqlpkg::Commands::UnsupportedPlatformException, Sqlpkg::Commands::ExecutableNotFoundException => e
  warn("ERROR: " + e.message)
  exit 1
end
